"""redcap_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from .views import *
from .test_view import *
from redcap_database import views, test_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home_page/', views.home_page, name='Home_Page'),
    path('home_page/applied_science_engineering_edit.html/', views.applied_science_engineering, name='Applied_Science_Engineering'),
    path('home_page/architecture.html/', views.architecture, name='Architecture'),
    path('home_page/convocation_office.html/', views.convocation_office, name='Convocation_Office'),
    path('home_page/dlsph.html/', views.dala_lana_school_of_public_health, name='Dala_Lana_School_of_Public_Health'),
    path('home_page/data_governance_group.html/', views.data_governance_group, name='Data_Governance_Group'),
    path('home_page/dentistry.html/', views.dentistry, name='Dentistry'),
    path('home_page/electrical_computer_eng.html/', views.electrical_computer_eng, name='Electrical_Computer_Eng'),
    path('home_page/hart_house.html/', views.hart_house, name='Harthouse'),
    path('home_page/i_school.html/', views.information, name='Information'),
    path('home_page/hpme.html/', views.health_policy_management_evaluation, name='Health_Policy_Management_Evaluation'),
    path('home_page/health_wellness.html/', views.health_wellness, name='Health_Wellness'),
    path('home_page/law.html/', views.law, name='Law'),
    path('home_page/mec_eng.html/', views.mechanical_industrial_eng, name='Mechanical_Industrial_Eng'),
    path('home_page/music.html/', views.music, name='Music'),
    path('home_page/nursing.html/', views.nursing, name='Nursing'),
    path('home_page/oise.html/', views.ontario_institute_for_studies_in_education, name='Ontario_Institute_for_Studies_in_Education'),
    path('home_page/pharmacy.html/', views.pharmacy, name='Pharmacy'),
    path('home_page/research_oversight_compliance.html/', views.research_oversight_compliance, name='Research_Oversight_Compliance'),
    path('home_page/rotman.html/', views.rotman, name='Rotman'),
    path('home_page/social_work.html/', views.social_work, name='Social_Work'),
    path('home_page/utm.html/', views.utm, name='UTM'),
    path('home_page/utsc_library.html/', views.utsc_library, name='UTSClibrary'),
    path('home_page/utsc.html/', views.utsc, name='UTSC'),
    path('home_page/anthropology.html/', views.anthropology, name='Anthropology'),
    path('home_page/art_history.html/', views.art_history, name='Art_History'),
    path('home_page/astronomy_astrophysics.html/', views.astronomy_astrophysics, name='Astronomy_Astrophysics'),
    path('home_page/cells_and_systems_biology.html/', views.cells_and_systems_biology, name='Cells_and_Systems_Biology'),
    path('home_page/chemistry.html/', views.chemistry, name='Chemistry'),
    path('home_page/classics.html/', views.classics, name='Classics'),
    path('home_page/computer_science.html/', views.computer_science, name='Computer_Science'),
    path('home_page/earth_sciences.html/', views.earth_sciences, name='Earth_Sciences'),
    path('home_page/east_asian_studies.html/', views.east_asian_studies, name='East_Asian_Studies'),
    path('home_page/ecology_and_evolutionary_biology.html/', views.ecology_and_evolutionary_biology, name='Ecology_and_Evolutionary_Biology'),
    path('home_page/economics.html/', views.economics, name='Economics'),
    path('home_page/english.html/', views.english, name='English'),
    path('home_page/french.html/', views.french, name='French'),
    path('home_page/geography_and_planning.html/', views.geography_and_planning, name='Geography_and_Planning'),
    path('home_page/germanic_language_and_literature.html/', views.germanic_language_and_literature, name='Germanic_Language_and_Literature'),
    path('home_page/history.html/', views.history, name='History'),
    path('home_page/italian_studies.html/', views.italian_studies, name='Italian_Studies'),
    path('home_page/linguistics.html/', views.linguistics, name='Linguistics'),
    path('home_page/mathematics.html/', views.mathematics, name='Mathematics'),
    path('home_page/nmec.html/', views.near_and_middle_eastern_civilizations, name='Near_and_Middle_Eastern_Civilizations'),
    path('home_page/philosophy.html/', views.philosophy, name='Philosophy'),
    path('home_page/physics.html/', views.physics, name='Physics'),
    path('home_page/political_science.html/', views.political_science, name='Political_Science'),
    path('home_page/psychology.html/', views.psychology, name='Psychology'),
    path('home_page/religion.html/', views.religion, name='Religion'),
    path('home_page/slavic_languages_and_literatures.html/', views.slavic_languages_and_literatures, name='Slavic_Language_and_Literatures'),
    path('home_page/sociology.html/', views.sociology, name='Sociology'),
    path('home_page/spanish_and_portuguese.html/', views.spanish_and_portuguese, name='Spanish_and_Portuguese'),
    path('home_page/statistical_sciences.html/', views.statistical_sciences, name='Statistical_Sciences'),
    path('home_page/centre_for_jewish_studies.html/', views.centre_for_jewish_studies, name='Centre_for_Jewish_Studies'),
    path('home_page/archaeology_centre.html/', views.archaeology_centre, name='Archaeology_Centre'),
    path('home_page/asian_institute.html/', views.asian_institute, name='Asian_Institute'),
    path('home_page/canadian_institute_for_theoretical_astrophysics.html/', views.canadian_institute_for_theoretical_astrophysics, name='Canadian_Institute_for_Theoretical_Astrophysics'),
    path('home_page/canadian_statistical_sciences_institute_ontario_regional_centre.html/', views.canadian_statistical_sciences_institute_ontario_regional_centre, name='Canadian_Statistical_Sciences_Institute_Ontario_Regional_Centre'),
    path('home_page/d_francophone.html/', views.d_etude_de_la_frances_et_du_monde_francophone, name='d_etude_de_la_Frances_et_du_monde_francophone'),
    path('home_page/centre_for_comparative_literature.html/', views.centre_for_comparative_literature, name='Centre_for_Comparative_Literature'),
    path('home_page/centre_for_criminology_and_sociolegal_studies.html/', views.centre_for_criminology_and_sociolegal_studies, name='Centre_for_Criminology_and_Sociolegal_studies'),
    path('home_page/centre_for_diaspora_and_transnational_studies.html/', views.centre_for_diaspora_and_transnational_studies, name='Centre_for_Diaspora_and_Transnational_studies'),
    path('home_page/centre_for_drama_theatre_performance_studies.html/', views.centre_for_drama_theatre_performance_studies, name='Centre_for_Drama_Theatre_Performance_studies'),
    path('home_page/centre_for_entrepreurship.html/', views.centre_for_entrepreurship, name='Centre_for_Entrepreneurship'),
    path('home_page/centre_for_ethics.html/', views.centre_for_ethics, name='Centre_for_Ethics'),
    path('home_page/centre_for_european_russion_eurasian_studies.html/', views.centre_for_european_russion_eurasian_studies, name='Centre_for_European_Russian_and_Eurasian_studies'),
    path('home_page/centre_for_global_change_science.html/', views.centre_for_global_change_science, name='Centre_for_Global_Change_Science'),
    path('home_page/centre_for_global_social_policy.html/', views.centre_for_global_social_policy, name='Centre_for_Global_Social_Policy'),
    path('home_page/centre_for_indigenous_studies.html/', views.centre_for_indigenous_studies, name='Centre_for_Indigenous_studies'),
    path('home_page/centre_for_industrial_relations_and_human_resources.html/', views.centre_for_industrial_relations_and_human_resources, name='Centre_for_Industrial_Relations_and_Human_Resources'),
    path('home_page/centre_for_medieval_studies.html/', views.centre_for_medieval_studies, name='Centre_for_Medieval_Studies'),
    path('home_page/centre_for_quantum_information_and_quantum_control.html/', views.centre_for_quantum_information_and_quantum_control, name='Centre_for_Quantum_Information_and_Quantum_Control'),
    path('home_page/centre_for_quantum_materials.html/', views.centre_for_quantum_materials, name='Centre_for_Quantum_materials'),
    path('home_page/centre_for_research_in_early_english_drama.html/', views.centre_for_research_in_early_english_drama, name='Centre_for_Research_in_Early_English_Drama'),
    path('home_page/centre_for_south_asian_studies.html/', views.centre_for_south_asian_studies, name='Centre_for_South_Asian_Studies'),
    path('home_page/centre_for_the_study_of_global_japan.html/', views.centre_for_the_study_of_global_japan, name='Centre_for_the_Study_of_Global_Japan'),
    path('home_page/centre_for_the_study_of_korea.html/', views.centre_for_the_study_of_korea, name='Centre_for_the_study_of_Korea'),
    path('home_page/centre_for_the_study_of_the_united_states.html/', views.centre_for_the_study_of_the_united_states, name='Centre_for_the_Study_of_the_United_States'),
    path('home_page/cinema_studies.html/', views.cinema_studies, name='Cinema_studies'),
    path('home_page/india_innovation_institute.html/', views.india_innovation_institute, name='India_Innovation_Institute'),
    path('home_page/institute_for_the_history_and_philosophy_of_science_and_technology.html/', views.institute_for_the_history_and_philosophy_of_science_and_technology, name='Institute_for_the_History_and_philosophy_of_science_and_technology'),
    path('home_page/institute_of_islamic_studies.html/', views.institute_of_islamic_studies, name='Institute_of_Islamic_Studies'),
    path('home_page/jackman_humanities_building.html/', views.jackman_humanities_building, name='Jackman_Humanities_Building'),
    path('home_page/koffler_scientific_reserve.html/', views.koffler_scientific_reserve, name='Koffler_Scientific_Reserve'),
    path('home_page/munk_school_of_global_affairs_and_publicpolicy.html/', views.munk_school_of_global_affairs_and_publicpolicy, name='Munk_School_of_Global_Affairs_and_PublicPolicy'),
    path('home_page/centre_for_buddhist_studies.html/', views.centre_for_buddhist_studies, name='Centre_for_Buddhist_Studies'),
    path('home_page/school_of_cities.html/', views.school_of_cities, name='School_of_Cities'),
    path('home_page/school_of_environment.html/', views.school_of_environment, name='School_of_Environment'),
    path('home_page/statistisc_canada_research_data_centre.html/', views.statistisc_canada_research_data_centre, name='Statisc_Canada_Research_Data_Centre'),
    path('home_page/trudeau_centre_for_peaceconflictjustice.html/', views.trudeau_centre_for_peaceconflictjustice, name='Trudeau_Centre_for_PeaceConflictJustice'),
    path('home_page/women_and_gender_studies_institute.html/', views.women_and_gender_studies_institute, name='Women_and_Gender_Studies_Institute'),
    path('home_page/urban_studies.html/', views.urban_studies, name='Urban_Studies'),
    path('home_page/writing_and_rhetoric.html/', views.writing_and_rhetoric, name='Writing_and_Rhetoric'),
    path('home_page/african_studies.html/', views.african_studies, name='African_studies'),
    path('home_page/buddhism_psychology_mental_health.html/', views.buddhism_psychology_mental_health, name='Buddhism_psychology_mental_health'),
    path('home_page/caribbean_studies.html/', views.caribbean_studies, name='Caribbean_studies'),
    path('home_page/equity_studies.html/', views.equity_studies, name='Equity_Studies'),
    path('home_page/book_and_media_studies.html/', views.book_and_media_studies, name='Book_and_Media_Studies'),
    path('home_page/celtic_studies.html/', views.celtic_studies, name='Celtic_Studies'),
    path('home_page/christianity_culture.html/', views.christianity_culture, name='Christianity_Culture'),
    path('home_page/medieval_studies.html/', views.medieval_studies, name='Medieval_Studies'),
    path('home_page/ethics_society_law.html/', views.ethics_society_law, name='Ethics_Society_Law'),
    path('home_page/international_relations.html/', views.international_relations, name='International_Relations'),
    path('home_page/canadian_studies.html/', views.canadian_studies, name='Canadian_Studies'),
    path('home_page/cognitive_science.html/', views.cognitive_science, name='Cognitive_Science'),
    path('home_page/health_studies.html/', views.health_studies, name='Health_Studies'),
    path('home_page/creative_expression_society.html/', views.creative_expression_society, name='Creative_Expression_Society'),
    path('home_page/education_society.html/', views.education_society, name='Education_Society'),
    path('home_page/literature_critical_theory.html/', views.literature_critical_theory, name='Literature_Critical_Theory'),
    path('home_page/material_culture.html/', views.material_culture, name='Material_Culture'),
    path('home_page/renaissance_studies.html/', views.renaissance_studies, name='Renaissance_Studies'),
    path('home_page/science_and_society.html/', views.science_and_society, name='Science_and_Society'),
    path('home_page/semiotics_and_communication_studies.html/', views.semiotics_and_communication_studies, name='Semiotics_and_Communication_Studies'),
    path('home_page/digitial_humanities.html/', views.digitial_humanities, name='Digital_Humanities'),
    path('home_page/medicine_admin.html/', views.medicine_admin, name='Medicine_Admin'),
    path('home_page/obstetrics_and_gynecology.html/', views.obstetrics_and_gynecology, name='Obstetrics_and_Gynecology'),
    path('home_page/family_community_medicine.html/', views.family_community_medicine, name='Family_Community_Medicine'),
    path('home_page/anesthesiology_pain_and_medicine.html/', views.anesthesiology_pain_and_medicine, name='Anesthesiology_pain_and_Medicine'),
    path('home_page/biochemistry.html/', views.biochemistry, name='Biochemistry'),
    path('home_page/biomedical_engineering.html/', views.biomedical_engineering, name='Biomedical_Engineering'),
    path('home_page/immunology.html/', views.immunology, name='Immunology'),
    path('home_page/laboratory_medicine_and_pathobiology.html/', views.laboratory_medicine_and_pathobiology, name='Laboratory_Medicine_and_Pathobiology'),
    path('home_page/medical_biophysics.html/', views.medical_biophysics, name='Medical_Biophysics'),
    path('home_page/medical_imaging.html/', views.medical_imaging, name='Medical_Imaging'),
    path('home_page/institute_of_medical_science.html/', views.institute_of_medical_science, name='Institute_Medical_Science'),
    path('home_page/molecular_genetics.html/', views.molecular_genetics, name='Molecular_Genetics'),
    path('home_page/nutritional_sciences.html/', views.nutritional_sciences, name='Nutritional_Sciences'),
    path('home_page/occupational_science_and_occupational_therapy.html/', views.occupational_science_and_occupational_therapy, name='Occupational_Science_and_Occupational_Therapy'),
    path('home_page/opthamalogy_and_vision_sciences.html/', views.opthamalogy_and_vision_sciences, name='Ophthamalogy_and_Vision_Sciences'),
    path('home_page/otolarynology_head_and_neck_surgery.html/', views.otolarynology_head_and_neck_surgery, name='Otolaryngology_Head_and_Neck_Surgery'),
    path('home_page/pediatrics.html/', views.pediatrics, name='Pediatrics'),
    path('home_page/pharmacology_and_toxicology.html/', views.pharmacology_and_toxicology, name='Pharmacology_and_Toxicology'),
    path('home_page/physical_therapy.html/', views.physical_therapy, name='Physical_Therapy'),
    path('home_page/physiology.html/', views.physiology, name='Physiology'),
    path('home_page/psychiatry.html/', views.psychiatry, name='Psychiatry'),
    path('home_page/radiation_oncology.html/', views.radiation_oncology, name='Radiation_Oncology'),
    path('home_page/rehabilitation.html/', views.rehabilitation, name='Rehabilitation'),
    path('home_page/speech_language_pathology.html/', views.speech_language_pathology, name='Speech_Language_Pathology'),
    path('home_page/surgery.html/', views.surgery, name='Surgery'),
    path('test_ui/', test_view.test_datalist, name='UI'),
    path('test_ui/applied_science_engineering_edit.html/', test_view.applied_science_engineering, name='Applied_Science_Engineering'),
    path('test_ui/architecture.html/', test_view.architecture, name='Architecture'),
    path('test_ui/convocation_office.html/', test_view.convocation_office, name='Convocation_Office'),
    path('test_ui/dlsph.html/', test_view.dala_lana_school_of_public_health, name='Dala_Lana_School_of_Public_Health'),






]
