# Generated by Django 3.0 on 2021-03-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0005_auto_20210321_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_science_engineering',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applied_science_engineering',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
