# Generated by Django 3.0 on 2021-03-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0006_auto_20210322_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied_science_engineering',
            name='user_name',
        ),
        migrations.AddField(
            model_name='applied_science_engineering',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applied_science_engineering',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
