# Generated by Django 3.0 on 2021-03-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0007_auto_20210322_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_science_engineering',
            name='project_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applied_science_engineering',
            name='project_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
