# Generated by Django 3.0 on 2021-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0008_auto_20210328_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_science_engineering',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='applied_science_engineering',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
    ]
