# Generated by Django 3.0 on 2021-04-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0009_auto_20210410_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_science_engineering',
            name='project_begin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applied_science_engineering',
            name='project_end',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
