# Generated by Django 3.0 on 2021-04-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0012_auto_20210410_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anthropology',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='anthropology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='art_history',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='art_history',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='astronomy_astrophysics',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='astronomy_astrophysics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='cells_and_systems_biology',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='cells_and_systems_biology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='classics',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='classics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='computer_science',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='computer_science',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='earth_sciences',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='earth_sciences',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='east_asian_studies',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='east_asian_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='ecology_and_evolutionary_biology',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='ecology_and_evolutionary_biology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='economics',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='economics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='english',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='english',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='french',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='french',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='geography_and_planning',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='geography_and_planning',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='germanic_language_and_literature',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='germanic_language_and_literature',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='italian_studies',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='italian_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='linguistics',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='linguistics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='mathematics',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='mathematics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='near_and_middle_eastern_civilizations',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='near_and_middle_eastern_civilizations',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='philosophy',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='philosophy',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='political_science',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='political_science',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='psychology',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='psychology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='slavic_languages_and_literatures',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='slavic_languages_and_literatures',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='sociology',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='sociology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='spanish_and_portuguese',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='spanish_and_portuguese',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='statistical_sciences',
            name='div_contact',
        ),
        migrations.RemoveField(
            model_name='statistical_sciences',
            name='user_name',
        ),
        migrations.AddField(
            model_name='anthropology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='anthropology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='anthropology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='anthropology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='art_history',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='art_history',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='art_history',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='art_history',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='astronomy_astrophysics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='astronomy_astrophysics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='astronomy_astrophysics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='astronomy_astrophysics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cells_and_systems_biology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cells_and_systems_biology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cells_and_systems_biology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cells_and_systems_biology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='classics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='classics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='classics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='classics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='computer_science',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='computer_science',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='computer_science',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='computer_science',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='earth_sciences',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='earth_sciences',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='earth_sciences',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='earth_sciences',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='east_asian_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='east_asian_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='east_asian_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='east_asian_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ecology_and_evolutionary_biology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ecology_and_evolutionary_biology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ecology_and_evolutionary_biology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ecology_and_evolutionary_biology',
            name='ufirst_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='economics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='economics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='economics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='economics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='english',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='english',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='english',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='english',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='french',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='french',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='french',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='french',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='geography_and_planning',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='geography_and_planning',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='geography_and_planning',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='geography_and_planning',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='germanic_language_and_literature',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='germanic_language_and_literature',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='germanic_language_and_literature',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='germanic_language_and_literature',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='history',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='history',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='history',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='history',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='italian_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='italian_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='italian_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='italian_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='linguistics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='linguistics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='linguistics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='linguistics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='mathematics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mathematics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mathematics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='mathematics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='near_and_middle_eastern_civilizations',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='near_and_middle_eastern_civilizations',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='near_and_middle_eastern_civilizations',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='near_and_middle_eastern_civilizations',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='philosophy',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='philosophy',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='philosophy',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='philosophy',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='physics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='physics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='physics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='physics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='political_science',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='political_science',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='political_science',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='political_science',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='psychology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='psychology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='psychology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='psychology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='religion',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='religion',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='religion',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='religion',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='slavic_languages_and_literatures',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='slavic_languages_and_literatures',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='slavic_languages_and_literatures',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='slavic_languages_and_literatures',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='sociology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sociology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sociology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='sociology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='spanish_and_portuguese',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='spanish_and_portuguese',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='spanish_and_portuguese',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='spanish_and_portuguese',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='statistical_sciences',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='statistical_sciences',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='statistical_sciences',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='statistical_sciences',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='anthropology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='anthropology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anthropology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='art_history',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='art_history',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='art_history',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='astronomy_astrophysics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='astronomy_astrophysics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='astronomy_astrophysics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cells_and_systems_biology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='cells_and_systems_biology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cells_and_systems_biology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='classics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computer_science',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='computer_science',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computer_science',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earth_sciences',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='earth_sciences',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earth_sciences',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='east_asian_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='east_asian_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='east_asian_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecology_and_evolutionary_biology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='ecology_and_evolutionary_biology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecology_and_evolutionary_biology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='economics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='english',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='english',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='english',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='french',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='french',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='french',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geography_and_planning',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='geography_and_planning',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geography_and_planning',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='germanic_language_and_literature',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='germanic_language_and_literature',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='germanic_language_and_literature',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='history',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='italian_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='italian_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='italian_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linguistics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='linguistics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linguistics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mathematics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='near_and_middle_eastern_civilizations',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='near_and_middle_eastern_civilizations',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='near_and_middle_eastern_civilizations',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='philosophy',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='philosophy',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='philosophy',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='physics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='political_science',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='political_science',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='political_science',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='psychology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='religion',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='religion',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='religion',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slavic_languages_and_literatures',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='slavic_languages_and_literatures',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slavic_languages_and_literatures',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sociology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='sociology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sociology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spanish_and_portuguese',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='spanish_and_portuguese',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spanish_and_portuguese',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistical_sciences',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='statistical_sciences',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistical_sciences',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
