# Generated by Django 3.0 on 2021-04-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0014_auto_20210410_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archaeology_centre',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='asian_institute',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='canadian_institute_for_theoretical_astrophysics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='canadian_statistical_sciences_institute_ontario_regional_centre',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_buddhist_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_comparative_literature',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_criminology_and_sociolegal_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_diaspora_and_transnational_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_drama_theatre_performance_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_entrepreneurship',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_ethics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_european_russian_and_eurasian_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_global_change_science',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_global_social_policy',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_indigenous_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_industrial_relations_and_human_resources',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_jewish_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_medieval_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_quantum_information_and_quantum_control',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_quantum_materials',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_research_in_early_english_drama',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_sexual_diversity_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_south_asian_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_the_study_of_global_japan',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_the_study_of_korea',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='centre_for_the_study_of_the_united_states',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='cinema_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='d_etude_de_la_frances_et_du_monde_francophone',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='india_innovation_institute',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='institute_for_the_history_and_philosophy_of_science_and_technology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='institute_of_islamic_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='jackman_humanities_building',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='koffler_scientific_reserve',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='munk_school_of_global_affairs_and_publicpolicy',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='school_of_cities',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='school_of_environment',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='statisc_canada_research_data_centre',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='trudeau_centre_for_peaceconflictjustice',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='women_and_gender_studies_institute',
            name='user_name',
        ),
        migrations.AddField(
            model_name='archaeology_centre',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='archaeology_centre',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='archaeology_centre',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='archaeology_centre',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='asian_institute',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='asian_institute',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='asian_institute',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='asian_institute',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='canadian_institute_for_theoretical_astrophysics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='canadian_institute_for_theoretical_astrophysics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='canadian_institute_for_theoretical_astrophysics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='canadian_institute_for_theoretical_astrophysics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='canadian_statistical_sciences_institute_ontario_regional_centre',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='canadian_statistical_sciences_institute_ontario_regional_centre',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='canadian_statistical_sciences_institute_ontario_regional_centre',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='canadian_statistical_sciences_institute_ontario_regional_centre',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_buddhist_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_buddhist_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_buddhist_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_buddhist_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_comparative_literature',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_comparative_literature',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_comparative_literature',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_comparative_literature',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_criminology_and_sociolegal_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_criminology_and_sociolegal_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_criminology_and_sociolegal_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_criminology_and_sociolegal_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_diaspora_and_transnational_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_diaspora_and_transnational_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_diaspora_and_transnational_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_diaspora_and_transnational_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_drama_theatre_performance_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_drama_theatre_performance_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_drama_theatre_performance_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_drama_theatre_performance_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_entrepreneurship',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_entrepreneurship',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_entrepreneurship',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_entrepreneurship',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_ethics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_ethics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_ethics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_ethics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_european_russian_and_eurasian_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_european_russian_and_eurasian_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_european_russian_and_eurasian_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_european_russian_and_eurasian_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_global_change_science',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_global_change_science',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_global_change_science',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_global_change_science',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_global_social_policy',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_global_social_policy',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_global_social_policy',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_global_social_policy',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_indigenous_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_indigenous_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_indigenous_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_indigenous_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_industrial_relations_and_human_resources',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_industrial_relations_and_human_resources',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_industrial_relations_and_human_resources',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_industrial_relations_and_human_resources',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_jewish_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_jewish_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_jewish_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_jewish_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_medieval_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_medieval_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_medieval_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_medieval_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_quantum_information_and_quantum_control',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_quantum_information_and_quantum_control',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_quantum_information_and_quantum_control',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_quantum_information_and_quantum_control',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_quantum_materials',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_quantum_materials',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_quantum_materials',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_quantum_materials',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_research_in_early_english_drama',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_research_in_early_english_drama',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_research_in_early_english_drama',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_research_in_early_english_drama',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_sexual_diversity_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_sexual_diversity_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_sexual_diversity_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_sexual_diversity_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_south_asian_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_south_asian_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_south_asian_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_south_asian_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_global_japan',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_global_japan',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_global_japan',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_global_japan',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_korea',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_korea',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_korea',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_korea',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_the_united_states',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_the_united_states',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_the_united_states',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='centre_for_the_study_of_the_united_states',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cinema_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cinema_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cinema_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cinema_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='d_etude_de_la_frances_et_du_monde_francophone',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='d_etude_de_la_frances_et_du_monde_francophone',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='d_etude_de_la_frances_et_du_monde_francophone',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='d_etude_de_la_frances_et_du_monde_francophone',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='india_innovation_institute',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='india_innovation_institute',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='india_innovation_institute',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='india_innovation_institute',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='institute_for_the_history_and_philosophy_of_science_and_technology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='institute_for_the_history_and_philosophy_of_science_and_technology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='institute_for_the_history_and_philosophy_of_science_and_technology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='institute_for_the_history_and_philosophy_of_science_and_technology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='institute_of_islamic_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='institute_of_islamic_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='institute_of_islamic_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='institute_of_islamic_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='jackman_humanities_building',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jackman_humanities_building',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='jackman_humanities_building',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='jackman_humanities_building',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='koffler_scientific_reserve',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='koffler_scientific_reserve',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='koffler_scientific_reserve',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='koffler_scientific_reserve',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='munk_school_of_global_affairs_and_publicpolicy',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='munk_school_of_global_affairs_and_publicpolicy',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='munk_school_of_global_affairs_and_publicpolicy',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='munk_school_of_global_affairs_and_publicpolicy',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='school_of_cities',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='school_of_cities',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='school_of_cities',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='school_of_cities',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='school_of_environment',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='school_of_environment',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='school_of_environment',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='school_of_environment',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='statisc_canada_research_data_centre',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='statisc_canada_research_data_centre',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='statisc_canada_research_data_centre',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='statisc_canada_research_data_centre',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='trudeau_centre_for_peaceconflictjustice',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trudeau_centre_for_peaceconflictjustice',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trudeau_centre_for_peaceconflictjustice',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='trudeau_centre_for_peaceconflictjustice',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='women_and_gender_studies_institute',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='women_and_gender_studies_institute',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='women_and_gender_studies_institute',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='women_and_gender_studies_institute',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='archaeology_centre',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='archaeology_centre',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archaeology_centre',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asian_institute',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='asian_institute',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asian_institute',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canadian_institute_for_theoretical_astrophysics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='canadian_institute_for_theoretical_astrophysics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canadian_institute_for_theoretical_astrophysics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canadian_statistical_sciences_institute_ontario_regional_centre',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='canadian_statistical_sciences_institute_ontario_regional_centre',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canadian_statistical_sciences_institute_ontario_regional_centre',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_buddhist_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_buddhist_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_buddhist_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_comparative_literature',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_comparative_literature',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_comparative_literature',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_criminology_and_sociolegal_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_criminology_and_sociolegal_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_criminology_and_sociolegal_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_diaspora_and_transnational_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_diaspora_and_transnational_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_diaspora_and_transnational_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_drama_theatre_performance_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_drama_theatre_performance_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_drama_theatre_performance_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_entrepreneurship',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_entrepreneurship',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_entrepreneurship',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_ethics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_ethics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_ethics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_european_russian_and_eurasian_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_european_russian_and_eurasian_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_european_russian_and_eurasian_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_global_change_science',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_global_change_science',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_global_change_science',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_global_social_policy',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_global_social_policy',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_global_social_policy',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_indigenous_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_indigenous_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_indigenous_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_industrial_relations_and_human_resources',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_industrial_relations_and_human_resources',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_industrial_relations_and_human_resources',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_jewish_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_jewish_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_jewish_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_medieval_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_medieval_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_medieval_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_quantum_information_and_quantum_control',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_quantum_information_and_quantum_control',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_quantum_information_and_quantum_control',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_quantum_materials',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_quantum_materials',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_quantum_materials',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_research_in_early_english_drama',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_research_in_early_english_drama',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_research_in_early_english_drama',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_sexual_diversity_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_sexual_diversity_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_sexual_diversity_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_south_asian_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_south_asian_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_south_asian_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_global_japan',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_global_japan',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_global_japan',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_korea',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_korea',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_korea',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_the_united_states',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_the_united_states',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='centre_for_the_study_of_the_united_states',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='cinema_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='d_etude_de_la_frances_et_du_monde_francophone',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='d_etude_de_la_frances_et_du_monde_francophone',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='d_etude_de_la_frances_et_du_monde_francophone',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='india_innovation_institute',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='india_innovation_institute',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='india_innovation_institute',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute_for_the_history_and_philosophy_of_science_and_technology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='institute_for_the_history_and_philosophy_of_science_and_technology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute_for_the_history_and_philosophy_of_science_and_technology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute_of_islamic_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='institute_of_islamic_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute_of_islamic_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jackman_humanities_building',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='jackman_humanities_building',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jackman_humanities_building',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='koffler_scientific_reserve',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='koffler_scientific_reserve',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='koffler_scientific_reserve',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='munk_school_of_global_affairs_and_publicpolicy',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='munk_school_of_global_affairs_and_publicpolicy',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='munk_school_of_global_affairs_and_publicpolicy',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_of_cities',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='school_of_cities',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_of_cities',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_of_environment',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='school_of_environment',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_of_environment',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisc_canada_research_data_centre',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='statisc_canada_research_data_centre',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisc_canada_research_data_centre',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trudeau_centre_for_peaceconflictjustice',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='trudeau_centre_for_peaceconflictjustice',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trudeau_centre_for_peaceconflictjustice',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='women_and_gender_studies_institute',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='women_and_gender_studies_institute',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='women_and_gender_studies_institute',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
