# Generated by Django 3.0 on 2021-04-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0016_auto_20210410_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='african_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='book_and_media_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='buddhism_psychology_mental_health',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='canadian_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='caribbean_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='celtic_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='christianity_culture',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='cognitive_science',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='creative_expression_society',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='digital_humanities',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='education_society',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='equity_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='ethics_society_law',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='health_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='international_relations',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='literature_critical_theory',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='material_culture',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='medieval_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='renaissance_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='science_and_society',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='semiotics_and_communication_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='urban_studies',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='writing_and_rhetoric',
            name='user_name',
        ),
        migrations.AddField(
            model_name='african_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='african_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='african_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='african_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='book_and_media_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='book_and_media_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='book_and_media_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='book_and_media_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='buddhism_psychology_mental_health',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='buddhism_psychology_mental_health',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='buddhism_psychology_mental_health',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='buddhism_psychology_mental_health',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='canadian_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='canadian_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='canadian_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='canadian_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='caribbean_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='caribbean_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='caribbean_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='caribbean_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='celtic_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='celtic_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='celtic_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='celtic_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='christianity_culture',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='christianity_culture',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='christianity_culture',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='christianity_culture',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cognitive_science',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cognitive_science',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cognitive_science',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='cognitive_science',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='creative_expression_society',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='creative_expression_society',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='creative_expression_society',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='creative_expression_society',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='digital_humanities',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='digital_humanities',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='digital_humanities',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='digital_humanities',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='education_society',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='education_society',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='education_society',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='education_society',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='equity_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='equity_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='equity_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='equity_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ethics_society_law',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ethics_society_law',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ethics_society_law',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ethics_society_law',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='health_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='health_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='health_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='health_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='international_relations',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='international_relations',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='international_relations',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='international_relations',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='literature_critical_theory',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='literature_critical_theory',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='literature_critical_theory',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='literature_critical_theory',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='material_culture',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='material_culture',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='material_culture',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='material_culture',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='medieval_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medieval_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='medieval_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='medieval_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='renaissance_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='renaissance_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='renaissance_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='renaissance_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='science_and_society',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='science_and_society',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='science_and_society',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='science_and_society',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='semiotics_and_communication_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='semiotics_and_communication_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='semiotics_and_communication_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='semiotics_and_communication_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='urban_studies',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='urban_studies',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='urban_studies',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='urban_studies',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='writing_and_rhetoric',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='writing_and_rhetoric',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='writing_and_rhetoric',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='writing_and_rhetoric',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='african_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='african_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='african_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_and_media_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='book_and_media_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_and_media_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buddhism_psychology_mental_health',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='buddhism_psychology_mental_health',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buddhism_psychology_mental_health',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canadian_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='canadian_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canadian_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caribbean_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='caribbean_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caribbean_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celtic_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='celtic_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celtic_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='christianity_culture',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='christianity_culture',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='christianity_culture',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cognitive_science',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='cognitive_science',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cognitive_science',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creative_expression_society',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='creative_expression_society',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creative_expression_society',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digital_humanities',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='digital_humanities',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digital_humanities',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education_society',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='education_society',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education_society',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equity_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='equity_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equity_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ethics_society_law',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='ethics_society_law',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ethics_society_law',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='health_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='international_relations',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='international_relations',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='international_relations',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literature_critical_theory',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='literature_critical_theory',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='literature_critical_theory',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material_culture',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='material_culture',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material_culture',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medieval_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='medieval_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medieval_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renaissance_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='renaissance_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renaissance_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='science_and_society',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='science_and_society',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='science_and_society',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semiotics_and_communication_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='semiotics_and_communication_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semiotics_and_communication_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urban_studies',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='urban_studies',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urban_studies',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writing_and_rhetoric',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='writing_and_rhetoric',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writing_and_rhetoric',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
