# Generated by Django 3.0 on 2021-04-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_database', '0018_auto_20210410_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anesthesiology_pain_and_medicine',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='biochemistry',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='biomedical_engineering',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='family_community_medicine',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='immunology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='institute_medical_science',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='laboratory_medicine_and_pathobiology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='medical_biophysics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='medical_imaging',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='medicine_admin',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='molecular_genetics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='nutritional_sciences',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='obstetrics_and_gynecology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='occupational_science_and_occupational_therapy',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='ophthamalogy_and_vision_sciences',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='otolaryngology_head_and_neck_surgery',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='pediatrics',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='pharmacology_and_toxicology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='physical_therapy',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='physiology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='psychiatry',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='radiation_oncology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='speech_language_pathology',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='user_name',
        ),
        migrations.AddField(
            model_name='anesthesiology_pain_and_medicine',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='anesthesiology_pain_and_medicine',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='anesthesiology_pain_and_medicine',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='anesthesiology_pain_and_medicine',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='biochemistry',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='biochemistry',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='biochemistry',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='biochemistry',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='biomedical_engineering',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='biomedical_engineering',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='biomedical_engineering',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='biomedical_engineering',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='family_community_medicine',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='family_community_medicine',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='family_community_medicine',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='family_community_medicine',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='immunology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='immunology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='immunology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='immunology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='institute_medical_science',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='institute_medical_science',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='institute_medical_science',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='institute_medical_science',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='laboratory_medicine_and_pathobiology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='laboratory_medicine_and_pathobiology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='laboratory_medicine_and_pathobiology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='laboratory_medicine_and_pathobiology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='medical_biophysics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medical_biophysics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='medical_biophysics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='medical_biophysics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='medical_imaging',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medical_imaging',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='medical_imaging',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='medical_imaging',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='medicine_admin',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine_admin',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='medicine_admin',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='medicine_admin',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='molecular_genetics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='molecular_genetics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='molecular_genetics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='molecular_genetics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='nutritional_sciences',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nutritional_sciences',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='nutritional_sciences',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='nutritional_sciences',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='obstetrics_and_gynecology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='obstetrics_and_gynecology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='obstetrics_and_gynecology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='obstetrics_and_gynecology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='occupational_science_and_occupational_therapy',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='occupational_science_and_occupational_therapy',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='occupational_science_and_occupational_therapy',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='occupational_science_and_occupational_therapy',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ophthamalogy_and_vision_sciences',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ophthamalogy_and_vision_sciences',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ophthamalogy_and_vision_sciences',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ophthamalogy_and_vision_sciences',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='otolaryngology_head_and_neck_surgery',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='otolaryngology_head_and_neck_surgery',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='otolaryngology_head_and_neck_surgery',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='otolaryngology_head_and_neck_surgery',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='pediatrics',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pediatrics',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pediatrics',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='pediatrics',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='pharmacology_and_toxicology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacology_and_toxicology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pharmacology_and_toxicology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='pharmacology_and_toxicology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='physical_therapy',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='physical_therapy',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='physical_therapy',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='physical_therapy',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='physiology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='physiology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='physiology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='physiology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='psychiatry',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='psychiatry',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='psychiatry',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='psychiatry',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='radiation_oncology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='radiation_oncology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='radiation_oncology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='radiation_oncology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='speech_language_pathology',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='speech_language_pathology',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='speech_language_pathology',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='speech_language_pathology',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='surgery',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='surgery',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='surgery',
            name='project_begin',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='surgery',
            name='project_end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='anesthesiology_pain_and_medicine',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='anesthesiology_pain_and_medicine',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anesthesiology_pain_and_medicine',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biochemistry',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='biochemistry',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biochemistry',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biomedical_engineering',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='biomedical_engineering',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biomedical_engineering',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family_community_medicine',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='family_community_medicine',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family_community_medicine',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='immunology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute_medical_science',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='institute_medical_science',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute_medical_science',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory_medicine_and_pathobiology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='laboratory_medicine_and_pathobiology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory_medicine_and_pathobiology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_biophysics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='medical_biophysics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_biophysics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_imaging',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='medical_imaging',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical_imaging',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_admin',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='medicine_admin',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_admin',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='molecular_genetics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='molecular_genetics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='molecular_genetics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritional_sciences',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='nutritional_sciences',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritional_sciences',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obstetrics_and_gynecology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='obstetrics_and_gynecology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obstetrics_and_gynecology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occupational_science_and_occupational_therapy',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='occupational_science_and_occupational_therapy',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occupational_science_and_occupational_therapy',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ophthamalogy_and_vision_sciences',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='ophthamalogy_and_vision_sciences',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ophthamalogy_and_vision_sciences',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otolaryngology_head_and_neck_surgery',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='otolaryngology_head_and_neck_surgery',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otolaryngology_head_and_neck_surgery',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pediatrics',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='pediatrics',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pediatrics',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacology_and_toxicology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='pharmacology_and_toxicology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacology_and_toxicology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physical_therapy',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='physical_therapy',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physical_therapy',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='physiology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physiology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychiatry',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='psychiatry',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychiatry',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiation_oncology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='radiation_oncology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiation_oncology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speech_language_pathology',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='speech_language_pathology',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speech_language_pathology',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='date_recorded',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='etoken_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='mfa_use',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
